name: Coverage
on:
  push:
    branches:
      - "*"
env:
  RUST_BACKTRACE: 1
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - nightly
        target:
          - x86_64-unknown-linux-gnu
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.15.0"

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
