name: Rust CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Set up Rust
            uses: actions/setup-rust@v1

        - name: Check out code
            uses: actions/checkout@v2

        - name: Build and test
            run: cargo test